# Generated by Django 5.1.3 on 2026-01-11 22:27

import companies.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='pełna nazwa firmy')),
                ('nip', models.CharField(max_length=20, verbose_name='nip firmy')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('main', 'main'), ('partner', 'partner'), ('basic', 'basic')], default='basic', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, default=companies.models.get_expiry_time)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('pl', 'Polish')], default='en', max_length=5)),
                ('company_status', models.CharField(choices=[('main', 'main'), ('partner', 'partner'), ('basic', 'basic')], default='basic', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.TextField(verbose_name='opis firmy')),
                ('logo_file', models.FileField(blank=True, upload_to='catalogue_logos', verbose_name='Logotyp do katalogu')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='nazwa (angielski)')),
                ('name_pl', models.CharField(max_length=255, verbose_name='nazwa (polski)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cena')),
                ('is_basic', models.BooleanField(default=False, verbose_name='wyposażenie podstawowe')),
                ('included_quantity', models.IntegerField(default=0, verbose_name='ilość wliczona (darmowa)')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='kategoria')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name_en'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='ilość')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('surname', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numer telefonu')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=50, verbose_name='etap formularza')),
                ('status', models.CharField(choices=[('pending', 'oczekiwanie na akceptację'), ('accepted', 'zaakceptowano'), ('rejected', 'wymagane poprawki')], default='pending', max_length=30)),
                ('comment', models.TextField(blank=True, verbose_name='komentarz')),
            ],
        ),
        migrations.CreateModel(
            name='FinalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('el_devices', models.CharField(max_length=255, verbose_name='urządzenia elektryczne w trakcie targów')),
                ('el_power', models.CharField(max_length=255, verbose_name='łączna moc urządzeń')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('stage_1', 'Dane podstawowe'), ('stage_2', 'Wyposażenie'), ('stage_3', 'Warsztaty'), ('stage_4', 'Jobwall'), ('stage_5', 'Inne dane'), ('completed', 'Zakończone')], default='stage_1', max_length=20)),
                ('stage_1_completed', models.BooleanField(default=False)),
                ('stage_2_completed', models.BooleanField(default=False)),
                ('stage_3_completed', models.BooleanField(default=False)),
                ('stage_4_completed', models.BooleanField(default=False)),
                ('stage_5_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jobwall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nazwa stanowiska')),
                ('form', models.CharField(choices=[('s', 'stacjonarnie'), ('z', 'zdalnie'), ('h', 'hybrydowo'), ('k', 'konkurs'), ('m', 'mobilnie')], max_length=50)),
                ('workload', models.CharField(choices=[('pelen', 'pełen etat'), ('pol', ' 1/2 etatu'), ('trzyczwarte', '3/4 etatu'), ('el', 'elastyczny')], max_length=50)),
                ('contract', models.CharField(choices=[('uop', 'umowa o pracę'), ('uoz', 'umowa o zlecenie'), ('uod', 'umowa o dzieło'), ('b2b', 'kontrakt b2b'), ('uos', 'umowa o staż/praktyki')], max_length=50)),
                ('description', models.TextField(verbose_name='opis stanowiska')),
                ('benefits', models.TextField(verbose_name='co jest oferowane')),
                ('requirements', models.TextField(verbose_name='wymagania')),
                ('url', models.CharField(max_length=500, verbose_name='application URL or email')),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('day1', '10.03.2025'), ('day2', '11.03.2025')], max_length=15)),
                ('lunch_quantity', models.IntegerField(verbose_name='liczba obiadów')),
                ('diet_info', models.CharField(blank=True, default='', max_length=255, verbose_name='informacje o dietach')),
            ],
        ),
        migrations.CreateModel(
            name='PDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_quantity', models.IntegerField(verbose_name='liczba biletów na galę PDI')),
            ],
        ),
        migrations.CreateModel(
            name='PDIAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('surname', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numer telefonu')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobwall_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Cena za jedno ogłoszenie jobwall', max_digits=10, verbose_name='cena za ogłoszenie jobwall')),
                ('lunch_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Cena za dodatkowy obiad (pierwsze 2 obiady dziennie są w pakiecie, czyli 4 obiady za 2 dni)', max_digits=10, verbose_name='cena za dodatkowy obiad')),
                ('stage_1_deadline', models.DateTimeField(blank=True, help_text='Globalny termin dla etapu 1 (Dane podstawowe)', null=True, verbose_name='termin etapu 1')),
                ('stage_2_deadline', models.DateTimeField(blank=True, help_text='Globalny termin dla etapu 2 (Wyposażenie)', null=True, verbose_name='termin etapu 2')),
                ('stage_3_deadline', models.DateTimeField(blank=True, help_text='Globalny termin dla etapu 3 (Warsztaty)', null=True, verbose_name='termin etapu 3')),
                ('stage_4_deadline', models.DateTimeField(blank=True, help_text='Globalny termin dla etapu 4 (Jobwall)', null=True, verbose_name='termin etapu 4')),
                ('stage_5_deadline', models.DateTimeField(blank=True, help_text='Globalny termin dla etapu 5 (Inne dane)', null=True, verbose_name='termin etapu 5')),
                ('day1_date', models.DateField(blank=True, help_text='Data pierwszego dnia targów (np. 2025-03-10)', null=True, verbose_name='dzień 1 targów')),
                ('day2_date', models.DateField(blank=True, help_text='Data drugiego dnia targów (np. 2025-03-11)', null=True, verbose_name='dzień 2 targów')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('day1', '10.03.2025'), ('day2', '11.03.2025')], max_length=15)),
                ('stand_number', models.CharField(blank=True, default='brak', max_length=10)),
                ('stand_size', models.CharField(choices=[('podstawowy', '4m2'), ('standardowy', '6m2'), ('rozszerzony', '8m2')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='StandDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand_type', models.CharField(choices=[('provided_stand', 'Provided Stand'), ('self_construction', 'Self Construction')], default='provided_stand', max_length=20, verbose_name='typ stanowiska')),
                ('sc_details', models.CharField(blank=True, max_length=255, verbose_name='z czego się składa własna zabudowa')),
                ('name_sign_text', models.CharField(blank=True, max_length=255, verbose_name='napis na fryz')),
                ('logo_sign_file', models.FileField(blank=True, upload_to='logos', verbose_name='Logotyp na fryz')),
                ('fire_cert', models.FileField(blank=True, upload_to='fire_certs', verbose_name='certyfikat o niepalności')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop', models.BooleanField(default=False, verbose_name='Poprowadzenie warsztatów')),
                ('notes', models.TextField(blank=True, verbose_name='dodatkowe uwagi')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='ulica')),
                ('home_number', models.CharField(max_length=10, verbose_name='numer domu')),
                ('apt_number', models.CharField(blank=True, max_length=10, verbose_name='numer lokalu')),
                ('city', models.CharField(max_length=100, verbose_name='miasto')),
                ('country', models.CharField(max_length=100, verbose_name='kraj')),
                ('postal_code', models.CharField(max_length=20, verbose_name='kod pocztowy')),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adress', to='companies.basicdata')),
            ],
        ),
    ]
