# Generated by Django 5.1.3 on 2025-10-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('main', 'main'), ('partener', 'partener'), ('basic', 'basic')], default='basic', max_length=10),
        ),
    ]
