# Generated by Django 5.1.3 on 2025-12-14 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fr_resp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fr_resp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='representative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp_repr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basicdata',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_data', to='companies.company'),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_ppl', to='companies.basicdata'),
        ),
        migrations.AddField(
            model_name='basicdata',
            name='dl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.deadline'),
        ),
        migrations.AddField(
            model_name='description',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='companies.company'),
        ),
        migrations.AddField(
            model_name='description',
            name='dl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.deadline'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='companies.company'),
        ),
        migrations.AddField(
            model_name='finaldata',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finaldata', to='companies.company'),
        ),
        migrations.AddField(
            model_name='finaldata',
            name='dl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.deadline'),
        ),
        migrations.AddField(
            model_name='jobwall',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobwalls', to='companies.company'),
        ),
        migrations.AddField(
            model_name='jobwall',
            name='dl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.deadline'),
        ),
        migrations.AddField(
            model_name='lunch',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunches', to='companies.finaldata'),
        ),
        migrations.AddField(
            model_name='pdi',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdis', to='companies.finaldata'),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitors', to='companies.pdi'),
        ),
        migrations.AddField(
            model_name='pdiattendee',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdiattendees', to='companies.pdi'),
        ),
        migrations.AddField(
            model_name='stand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stand_all', to='companies.company'),
        ),
        migrations.AddField(
            model_name='standdetails',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stand_details', to='companies.company'),
        ),
        migrations.AddField(
            model_name='standdetails',
            name='dl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.deadline'),
        ),
        migrations.AddField(
            model_name='extendedequipment',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ext_equipment', to='companies.standdetails'),
        ),
        migrations.AddField(
            model_name='basicequipment',
            name='form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='basic_equipment', to='companies.standdetails'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='companies.company'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='dl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.deadline'),
        ),
    ]
