# Generated by Django 6.0.7 on 2026-08-07 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdata',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='basic_data', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basicdata',
            name='dl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.deadline'),
        ),
        migrations.AddField(
            model_name='company',
            name='fr_resp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fr_resp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='representative',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comp_repr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyinvitation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='description',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='description', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='description',
            name='dl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.deadline'),
        ),
        migrations.AddField(
            model_name='equipmentselection',
            name='equipment_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='companies.equipmentitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipmentselection',
            name='stand_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_selections', to='companies.standdetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exhibitors', to='companies.pdi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finaldata',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='finaldata', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finaldata',
            name='dl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.deadline'),
        ),
        migrations.AddField(
            model_name='form',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='form', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobwall',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobwalls', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobwall',
            name='dl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.deadline'),
        ),
        migrations.AddField(
            model_name='lunch',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lunches', to='companies.finaldata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdi',
            name='form',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pdis', to='companies.finaldata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdiattendee',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pdiattendees', to='companies.pdi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stand',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stand_all', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standdetails',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stand_details', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standdetails',
            name='dl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.deadline'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshop',
            name='dl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.deadline'),
        ),
        migrations.AlterField(
            model_name='stand',
            name='stand_size',
            field=models.CharField(choices=[('podstawowy', '4m2'), ('standardowy', '6m2'), ('rozszerzony', '8m2'), ('12m2', '12m2')], max_length=11),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentselection',
            unique_together={('stand_details', 'equipment_item')},
        ),
    ]
