# Generated by Django 5.1.3 on 2025-11-18 20:23

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=255)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 25, 20, 23, 48, 167977, tzinfo=datetime.timezone.utc))),
                ('is_accepted', models.BooleanField(default=False)),
                ('company_status', models.CharField(choices=[('main', 'main'), ('partner', 'partner'), ('basic', 'basic')], default='basic', max_length=10)),
            ],
        ),
    ]
