# Generated by Django 5.1.3 on 2025-12-10 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinvitation',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 17, 23, 43, 56, 271555, tzinfo=datetime.timezone.utc)),
        ),
    ]
