# Generated by Django 5.1.3 on 2025-10-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('main', 'main'), ('partner', 'partner'), ('basic', 'basic')], default='basic', max_length=10),
        ),
    ]
