# Generated by Django 6.0.7 on 2026-08-20 00:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_sync_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='invitation_reminder_1_days',
            field=models.PositiveSmallIntegerField(blank=True, default=2, null=True, verbose_name='przypomnienie 1 (dni przed wygaśnięciem)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='invitation_reminder_2_days',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='przypomnienie 2 (dni przed wygaśnięciem)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='invitation_reminder_3_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='przypomnienie 3 (dni przed wygaśnięciem)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='invitation_reminder_4_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='przypomnienie 4 (dni przed wygaśnięciem)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='invitation_reminder_5_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='przypomnienie 5 (dni przed wygaśnięciem)'),
        ),
        migrations.AddField(
            model_name='settings',
            name='invitation_reminder_count',
            field=models.PositiveSmallIntegerField(default=2, help_text='Set to 0 to disable invitation expiry reminders.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='liczba przypomnień o wygaśnięciu'),
        ),
        migrations.AddField(
            model_name='settings',
            name='invitation_validity_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='Liczba dni ważności nowo wysłanych linków zaproszenia (1–30). Nie zmienia już wysłanych zaproszeń.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='ważność zaproszenia (dni)'),
        ),
        migrations.CreateModel(
            name='InvitationExpiryReminderSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before', models.PositiveSmallIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiry_reminders_sent', to='companies.companyinvitation')),
            ],
            options={
                'unique_together': {('invitation', 'days_before')},
            },
        ),
    ]
