# Generated by Django 6.0.7 on 2026-08-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_settings_email_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationexpiryremindersent',
            name='recipient',
            field=models.CharField(
                choices=[('exhibitor', 'Exhibitor'), ('staff', 'Staff')],
                default='exhibitor',
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='invitationexpiryremindersent',
            unique_together={('invitation', 'days_before', 'recipient')},
        ),
    ]
