# Generated by Django 6.0.7 on 2026-08-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_limit_invitation_reminders_to_3'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitationexpiryremindersent',
            options={'verbose_name': 'Company reminder', 'verbose_name_plural': 'Company reminders'},
        ),
        migrations.AlterField(
            model_name='lunch',
            name='day',
            field=models.CharField(choices=[('day1', '09.03.2027'), ('day2', '10.03.2027')], max_length=15),
        ),
        migrations.AlterField(
            model_name='stand',
            name='day',
            field=models.CharField(choices=[('day1', '09.03.2027'), ('day2', '10.03.2027')], max_length=15),
        ),
    ]
