# Generated by Django 5.1.3 on 2026-08-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_day_choices_and_reminder_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='code',
            field=models.SlugField(blank=True, help_text='Stabilny identyfikator reguł: hanger, trashbin, tv, square_table, arc_counter', null=True, unique=True, verbose_name='kod (slug)'),
        ),
        migrations.AddField(
            model_name='equipmentselection',
            name='mount_type',
            field=models.CharField(blank=True, choices=[('stand', 'Na stojaku'), ('wall', 'Na ścianie')], max_length=20, null=True, verbose_name='typ montażu (TV)'),
        ),
        migrations.AddField(
            model_name='standdetails',
            name='brought_equipment',
            field=models.TextField(blank=True, verbose_name='sprzęt przywożony przez firmę'),
        ),
        migrations.AddField(
            model_name='standdetails',
            name='stand_visualization',
            field=models.FileField(blank=True, upload_to='stand_visualizations', verbose_name='wizualizacja stoiska'),
        ),
    ]
