# Generated by Django 5.1.3 on 2026-08-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_stage2_stand_visualization_equipment_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentitem',
            name='code',
            field=models.SlugField(blank=True, help_text='Puste = zwykła pozycja bez ekstra reguł. Wpisz dokładnie jeden kod: hanger — wieszak (1 w pakiecie; ukryty przy własnej zabudowie); trashbin — kosz (zawsze 1 w pakiecie); tv — wybór montażu stojak/ściana; square_table — stolik kwadrat; arc_counter — ostrzeżenie: głównie stoiska narożne.', null=True, unique=True, verbose_name='kod specjalnych właściwości'),
        ),
    ]
