name: pipeline
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v2
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and publish backend image
        id: build-push-backend
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:backend"
          file: Dockerfile
          push: true
          tags: 0noder4/itp_system32_backend:dev_${{ github.run_number }}
