name: pipeline
on:
  push:
    branches:
      - develop
  workflow_dispatch:
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Load .env file
        uses: xom9ikk/dotenv@v2.3.0
        with:
          mode: development
          load-mode: strict
      - name: Print env
        run: echo "${{env.backend_version}}"
